version: "3.9"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: my-db
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-password
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  db_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: my-db
      POSTGRES_USER: my-user
      POSTGRES_PASSWORD: my-password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
